### PR TITLE
[tools]: Bump LLVM to mainline

### PR DESCRIPTION
**Pull request by Avimitin**
This commit add metals for scala, and bump buddy-mlir to latest commit to have buddy-lsp-server for mlir.

To have buddy-lsp-server working, this pr also bump llvm to mainline version to have I2p1 extension support.

### CODE REVIEW

**Review by sequencer — APPROVED** [review]

**Comment by SharzyL** [comment]
Now that we have two LLVM versions, we'd better to clarify the usages of them. Currently

1. `myLLVM` (i.e. LLVM 17) is used to compile rv32 elf.
2. `legacyLLVM` (i.e. LLVM 14) is used to compile `rv32-musl`, `rv32-compilerrt`, and in development shell.

(there is also a LLVM used to compile buddy, but not discussed here)

Their namings are a little bit confusing. I would suggest renaming the former to `LLVMToolsForRV32Clang`, and the later to `LLVMForDev`

**Comment by Avimitin** [comment]
All variable names are updated in the latest commit. Please do a new review, thanks. And if everything works fine, please merge #235 before this PR. There is an illegal MLIR op in this old testcase and the test can't pass in the latest buddy-mlir. And the axpy-masked.mlir case will also fail, but it is not related to this PR. @xlinsist will fix the test later.

**Comment by Avimitin** [comment]
Update: @xlinsist fixed the instruction issue in #236, please merge both #235 and #236 before this PR.

**Comment by Avimitin** [comment]
Conflicts are all resolved, ready for new review.

**Comment by Avimitin** [comment]
Intrinsic test case is fixed, ready for new review.

**Review by sequencer — APPROVED** [review]
LGTM

**Pull request merged**
